### ISSUE TITLE
Unbreakable lamp posts

### ISSUE THREAD

**Issue by turret001** [Wolfee-J/MTA-Vice-City#3]
![image](https://user-images.githubusercontent.com/24281147/86133119-8edd3300-baf0-11ea-8438-3d0bcb9e11d6.png)

Model ID: 1295 or 1296

These lamp posts are unbreakable. They act like a wall and when a car hits them, car gets damaged like it hit a wall.

**Comment by Wolfee-J** [comment]
It's an SA issue, won't fix.
